### ISSUE TITLE
Feature: CI/CD

### ISSUE THREAD

**Issue by menisisaac** [menisisaac/Infa--#3]
# Epic Title

Feature: CI/CD

## Epic Description

This Feature will...

## List of Tasks (Complete in order)

1. [ ] [Task 1: CMake for building](https://github.com/username/repository-name/issues/1)
2. [ ] [Task 2: CMake for testing](https://github.com/username/repository-name/issues/2)
3. [ ] [Task 3: C++ linter](https://github.com/username/repository-name/issues/3)
4. [ ] [Task 4: Configure LLVM](https://github.com/username/repository-name/issues/4)
5. [ ] [Task 5: Github Actions CMake Tests](https://github.com/username/repository-name/issues/5)
6. [ ] [Task 6: Github Actions Release](https://github.com/username/repository-name/issues/6)
